### PR TITLE
Update to content for the poison centre user declaration

### PR DESCRIPTION
**Pull request by frankieroberto**
## Before

Screenshot 2019-10-28 at 09 26 49

## After

Screenshot 2019-10-28 at 09 31 34

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-635

Review app: https://cosmetics-pr-1432-search-web.london.cloudapps.digital

### CODE REVIEW

**Comment by nasirkhanbeis** [comment]
@frankieroberto  is the review up and running? doesn't exist it seems.

**Comment by frankieroberto** [comment]
@nasirkhanbeis hmm, doesn’t seem so. I've re-requested the build. You can follow along here: https://travis-ci.org/UKGovernmentBEIS/beis-opss/builds/603861739 – should create a review app within about 10-15 mins.

**Comment by nasirkhanbeis** [comment]
@frankieroberto  Looking good as expected, just to a minor issue, check box to read as "I agree"

**Comment by frankieroberto** [comment]
@nasirkhanbeis thanks, that wording will change as part of #1434, so let's get that merged first.

**Pull request merged**
