### PR TITLE
Update content on search homepage

### PR DESCRIPTION
**Pull request by frankieroberto**
## Before

before

## After

after

Review app: https://cosmetics-pr-1461-search-web.london.cloudapps.digital

https://regulatorydelivery.atlassian.net/jira/software/projects/COSBETA/boards/24?selectedIssue=COSBETA-598

### CODE REVIEW

**Comment by tobyhughes** [comment]
@frankieroberto could you include a screenshot when the changes have been made, please?

**Comment by PabCab** [comment]
A few tweaks please.

(i) Needs 'How to access the service' h2 after lead content.

(ii) Content in this section has changed to:

<h2>How to access the service</h2>

If you're using this service for the first time, send an email to <a href="mailto:opss.enquiries@beis.gov.uk">opss.enquiries@beis.gov.uk</a> to ask for an account.

<h3>Trading Standards officers</h3>

If you've used the Product Safety Database (PSD), you can use your PSD sign in details (username and password).

(ii) In the 'What you can search for' section:

<h3>NPIS staff</h3>

change to

<h3>National Poison Information Service (NPIS) staff</h3>

Thanks

**Comment by PabCab** [comment]
Can 'How to access the service' be an h2?

**Comment by PabCab** [comment]
Looks good to me Frankie. Thank you.

**Pull request merged**
